package model;


import java.time.LocalDate;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;


/**
 * Apartment generated by hbm2java
 */
public class Apartment implements java.io.Serializable {

	private Integer apartmentId;
	private Integer baseCapacity;
	private Integer additionalCapacity;
	private String apartmentName;
	private String internalName;
	private String apartmentNote;
	private Set pricepernights = new HashSet(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	private Map<LocalDate, Reservation> apartmentReservations = new HashMap<LocalDate, Reservation>();

	public Apartment() {
	}

	public Apartment(Integer apartmentId, Integer baseCapacity, Integer additionalCapacity
			, String apartmentName, String internalName, String apartmentNote, Set pricepernights) {
		this.apartmentId = apartmentId;
		this.baseCapacity = baseCapacity;
		this.additionalCapacity = additionalCapacity;
		this.apartmentName = apartmentName;
		this.internalName = internalName;
		this.apartmentNote = apartmentNote;
		this.pricepernights = pricepernights;
	}

	public Integer getApartmentId() {
		return this.apartmentId;
	}

	public void setApartmentId(Integer apartmentId) {
		this.apartmentId = apartmentId;
	}

	public Integer getBaseCapacity() {
		return this.baseCapacity;
	}

	public void setBaseCapacity(Integer baseCapacity) {
		this.baseCapacity = baseCapacity;
	}

	public Integer getAdditionalCapacity() {
		return this.additionalCapacity;
	}

	public void setAdditionalCapacity(Integer additionalCapacity) {
		this.additionalCapacity = additionalCapacity;
	}

	public String getApartmentName() {
		return this.apartmentName;
	}

	public void setApartmentName(String apartmentName) {
		this.apartmentName = apartmentName;
	}

	public String getInternalName() {
		return this.internalName;
	}

	public void setInternalName(String internalName) {
		this.internalName = internalName;
	}

	public String getApartmentNote() {
		return this.apartmentNote;
	}

	public void setApartmentNote(String apartmentNote) {
		this.apartmentNote = apartmentNote;
	}

	public Set getPricepernights() {
		return this.pricepernights;
	}

	public void setPricepernights(Set pricepernights) {
		this.pricepernights = pricepernights;
	}

	public Map<LocalDate, Reservation> getApartmentReservations() {
		return apartmentReservations;
	}

    @Override
    public String toString() {
        return "Apartment{" +
                "apartmentId=" + apartmentId +
                ", baseCapacity=" + baseCapacity +
                ", additionalCapacity=" + additionalCapacity +
                ", apartmentName='" + apartmentName + '\'' +
                ", internalName='" + internalName + '\'' +
                ", apartmentNote='" + apartmentNote + '\'' +
                ", pricepernights=" + pricepernights +
                ", reservations=" + reservations +
                ", apartmentReservations=" + apartmentReservations +
                '}';
    }
}
