package model;


import java.math.BigDecimal;
import java.util.Date;


/**
 * Pricepernight generated by hbm2java
 */

public class PricePerNight implements java.io.Serializable {

	private PricepernightId id;

	private Apartment apartment;
	private Date priceTo;
	private BigDecimal price;

	public PricePerNight() {
	}

	public PricePerNight(PricepernightId id, Apartment apartment) {
		this.id = id;
		this.apartment = apartment;
	}

	public PricePerNight(PricepernightId id, Apartment apartment, Date priceTo, BigDecimal price) {
		this.id = id;
		this.apartment = apartment;
		this.priceTo = priceTo;
		this.price = price;
	}

	public PricepernightId getId() {
		return this.id;
	}

	public void setId(PricepernightId id) {
		this.id = id;
	}

	
	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}
	

	public Date getPriceTo() {
		return this.priceTo;
	}

	public void setPriceTo(Date priceTo) {
		this.priceTo = priceTo;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
