package model;
import java.util.HashSet;
import java.util.Set;

/**
 * Tourists generated by hbm2java
 */

public class Tourists implements java.io.Serializable {

	private Long touristsId;
	private String name;
	private String country;
	private String city;
	private Integer numberOfAdults;
	private Integer numberOfChildren;
	private Integer numberOfPersons;
	private String email;
	private String phoneNumber;
	private Boolean pets;
	private String touristsNote;
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Tourists() {
	}

	public Tourists(String name) {
		this.name = name;
	}

	public Tourists(Long touristsId, String name, String country, String city, Integer numberOfAdults, Integer numberOfChildren,
			Integer numberOfPersons, String email, String phoneNumber, Boolean pets, String touristsNote
			/*Set reservations*/) {
		this.touristsId = touristsId;
		this.name = name;
		this.country = country;
		this.city = city;
		this.numberOfAdults = numberOfAdults;
		this.numberOfChildren = numberOfChildren;
		this.numberOfPersons = numberOfPersons;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.pets = pets;
		this.touristsNote = touristsNote;
		//this.reservations = reservations;
	}

	public Long getTouristsId() {
		return this.touristsId;
	}

	public void setTouristsId(Long touristsId) {
		this.touristsId = touristsId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getNumberOfAdults() {
		return this.numberOfAdults;
	}

	public void setNumberOfAdults(Integer numberOfAdults) {
		this.numberOfAdults = numberOfAdults;
	}

	public Integer getNumberOfChildren() {
		return this.numberOfChildren;
	}

	public void setNumberOfChildren(Integer numberOfChildren) {
		this.numberOfChildren = numberOfChildren;
	}

	public Integer getNumberOfPersons() {
		return this.numberOfPersons;
	}

	public void setNumberOfPersons(Integer numberOfPersons) {
		this.numberOfPersons = numberOfPersons;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public Boolean getPets() {
		return this.pets;
	}

	public void setPets(Boolean pets) {
		this.pets = pets;
	}

	public String getTouristsNote() {
		return this.touristsNote;
	}

	public void setTouristsNote(String touristsNote) {
		this.touristsNote = touristsNote;
	}

	/*
	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}
	*/

	@Override
	public String toString() {
		return "Tourists{" +
				"touristsId=" + touristsId +
				", name='" + name + '\'' +
				", country='" + country + '\'' +
				", city='" + city + '\'' +
				", numberOfAdults=" + numberOfAdults +
				", numberOfChildren=" + numberOfChildren +
				", numberOfPersons=" + numberOfPersons +
				", email='" + email + '\'' +
				", phoneNumber='" + phoneNumber + '\'' +
				", pets=" + pets +
				", touristsNote='" + touristsNote + '\'' +
				", reservations=" + reservations +
				'}';
	}
}
